name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and deploy with Docker Compose
        run: |
          git clone https://github.com/ghuzed/log430-a25-labo0.git
          cd log430-a25-labo0
          git pull
          docker build -t labo0-calculator .
          docker compose up
